#############################################
##### Inspecting Ferkingstad duplicates  ####
#############################################

## Guillermo Reales
## 2022-06-09

# We will inspect the Manhattan plots of several duplicated traits of interest in Ferkingstad et al. for the cytokine basis project.
# These duplicates are generated by using aptamers that target more than one (and osmetimes, overlapping) proteins.
# We'll look at the Manhattan plots to see if there are differences in the hits that can help us pick.

##############################################
##### Load functions                   #######
##############################################

library(data.table)
setDTthreads(10)
library(karyoploteR)
library(GenomicRanges)

##############################################


create.b2b.manhattan <- function(ids, path){
	
	f1 = dir(path = path, pattern = ids[1])
	f2 = dir(path = path, pattern = ids[2])
	message("Working on manhattan plot for ", f1," and ", f2)

	d1 <- fread(paste0(path, f1), tmpdir = "tmp") 
	d2 <- fread(paste0(path, f2), tmpdir = "tmp")

	s1  <- GRanges(seqnames=d1$Chrom, ranges=IRanges(start=d1$Pos, end=d1$Pos), strand="*")
	s1$pval  <- d1$Pval
	s2  <- GRanges(seqnames=d2$Chrom, ranges=IRanges(start=d2$Pos, end=d2$Pos), strand="*")
	s2$pval  <- d2$Pval

	png(filename=paste0(ids[1],"-", ids[2], ".manhattanplot.png"), width=12, height=8, units="in", res=300)
	kp <- plotKaryotype(plot.type=4)
	kpAddLabels(kp, labels = ids[1], srt=90, pos=3, r0=0.5, r1=1, cex=1.8, label.margin = 0.025)
	kpAxis(kp, ymin=0, ymax=15, r0=0.5)
	kp <- kpPlotManhattan(kp, data=s1,  r0=0.5, r1=1, ymax=10, points.col = "brewer.set1")
	kpAddLabels(kp, labels = ids[2], srt=90, pos=3, r0=0, r1=0.5, cex=1.8, label.margin = 0.025)
	kpAxis(kp, ymin=0, ymax=15, r0=0.5, r1=0, tick.pos = c(5,10))
	kp <- kpPlotManhattan(kp, data=s2, r0=0.5, r1=0, ymax=10, points.col = "2blues")
	dev.off()	
}

path = '~/rds/rds-cew54-wallace-share/Data/GWAS-summary/Ferkingstad_proteins/'

dups = list(c("5355_69","5988_49"),
c("14063_17","2693_20"),
c("5947_90","8059_1"),
c("2913_1","3028_36"),
c("11593_21","9188_119"))

lapply(dups, function(x){ create.b2b.manhattan(ids=x, path=path) })

