#!/bin/bash
#SBATCH -J lift19
#SBATCH -A CWALLACE-SL2-CPU
#SBATCH --nodes 1
#SBATCH --ntasks 8
#SBATCH --time 00:10:00
#SBATCH --mail-type FAIL
#SBATCH -p skylake
#SBATCH --output=./err/%A_%a.err
shopt -s nullglob
. /etc/profile.d/modules.sh # Leave this line (enables the module command)
module purge                # Removes all modules still loaded
#module load default-impi    # REQUIRED - loads the basic environment
module load rhel7/default-peta4            # REQUIRED - loads the basic environment
module load r-4.0.2-gcc-5.4.0-xyx46xb
module load plink/2.00-alpha
export I_MPI_PIN_ORDER=scatter # Adjacent domains have minimal sharing of caches/sockets
JOBID=$SLURM_JOB_ID
echo -e "JobID: $JOBID"
G=$SLURM_ARRAY_TASK_ID ### this is the array variable, you can use it the way you want. In this example I use it to select the gene based on the line number in a file
F=$(($G - 1)) # Zero based array
a=(*-hg38.tsv.gz)
fname=${a[$F]}

~/rds/rds-cew54-basis/GWAS_tools/02c-Backliftover_hg19/liftover-hg38-hg19.sh -f $fname 


