#!/bin/bash
#SBATCH -J RCBv2c
#SBATCH -A CWALLACE-SL3-CPU
#SBATCH --nodes 1
#SBATCH --ntasks 8
#SBATCH --time 00:20:00
#SBATCH --mail-type FAIL
#SBATCH -p skylake-himem
#SBATCH --output=./err/RCBv2/%A_%a.err
. /etc/profile.d/modules.sh # Leave this line (enables the module command)
module purge                # Removes all modules still loaded
#module load default-impi    # REQUIRED - loads the basic environment
module load rhel7/default-peta4            # REQUIRED - loads the basic environment
module load r-4.0.2-gcc-5.4.0-xyx46xb
export I_MPI_PIN_ORDER=scatter # Adjacent domains have minimal sharing of caches/sockets
JOBID=$SLURM_JOB_ID
echo -e "JobID: $JOBID"
G=$SLURM_ARRAY_TASK_ID ### this is the array variable, you can use it the way you want. In this example I use it to select the gene based on the line number in a file
Rscript /home/gr440/rds/rds-cew54-basis/GWAS_tools/04-Reduction/Reducing_all_for_cellbasis_v2_collector.R  $G
